version: '3'
services:
  chall:
    build: .
    ports:
      - 10001:10001
    read_only: true
    cap_drop:
      - all
              
    restart: on-failure

    deploy:
        resources:
            limits:
              cpus: '0.2'
              memory: 1000M